dist: xenial
os: linux
language: python
python:
    - 3.8

services:
    - docker

script:
    - coverage run -m pytest

after_success:
    - bash <(curl -s https://codecov.io/bash)

deploy:
    provider: script
    script: bash docker/heroku_push.sh
    cleanup: true
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH = master || $TRAVIS_BRANCH = develop
