dist: xenial
os: linux
language: python
python:
  - 3.8

services:
  - docker

script:
  - python -m pytest tests

deploy:
    provider: script
    script: bash docker/heroku_push.sh
    cleanup: true
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH = master || $TRAVIS_BRANCH = develop
