version: '3.7'

services:
  project:
    image: python:3.8.6-slim-buster
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - db
    working_dir: /app
    command: ./run_dev.sh

  db:
    container_name: db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project

volumes:
  postgres_data:
