version: '3.7'

services:
  project:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project

volumes:
  postgres_data:
