"""add_user_role

Revision ID: 0697a5c45603
Revises: bc8564bdf511
Create Date: 2020-10-28 14:25:30.110880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0697a5c45603'
down_revision = 'bc8564bdf511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=128)))

    op.execute('UPDATE users SET role=\'guest\' WHERE role IS NULL')

    # needed due to sqlite limitations
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
