"""add_user_fields

Revision ID: 34eebaeb9eb9
Revises: 0697a5c45603
Create Date: 2020-11-09 00:43:12.609976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34eebaeb9eb9'
down_revision = '0697a5c45603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=128), nullable=True))

    op.add_column('users', sa.Column('surname', sa.String(length=128)))
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('role', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
