"""server_block

Revision ID: 5ba9ea52200d
Revises: 113f1412c360
Create Date: 2021-03-08 00:36:39.294960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba9ea52200d'
down_revision = '113f1412c360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('blocked', sa.Boolean()))
    op.execute('UPDATE servers SET blocked=false WHERE blocked IS NULL')

    with op.batch_alter_table('servers') as batch_op:
        batch_op.alter_column('blocked', nullable=False)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='unique')
    op.drop_column('servers', 'blocked')
    # ### end Alembic commands ###
