"""user_id

Revision ID: 6216b0fe5ac7
Revises: 34eebaeb9eb9
Create Date: 2020-11-13 23:19:17.576471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6216b0fe5ac7'
down_revision = '34eebaeb9eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
