"""user_block

Revision ID: e887ca8f1c99
Revises: 16c43495b878
Create Date: 2021-02-21 16:56:43.170501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e887ca8f1c99'
down_revision = '16c43495b878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked')
    # ### end Alembic commands ###
