name: build
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run test suite
        run: |
          export PATH="$PATH:/home/runner/.local/bin"
          pip install -r requirements.txt --user
          coverage run -a -m pytest
      - name: Send coverage report
        run: ls -la && bash <(curl -s https://codecov.io/bash)

  deploy:
    runs-on: ubuntu-20.04
    needs: test
    if: contains('
      refs/heads/master
      refs/heads/develop
      ', github.ref)
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Deploy app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          export BRANCH=${GITHUB_REF##*/}
          docker/heroku_push.sh
